### ISSUE TITLE
 PHP Warning: Undefined array key "svgstore." in vendor/lochmueller/sourceopt/Classes/Resource  /SvgFileRepository.php line 43

### ISSUE THREAD

**Issue by siwa-pparzer** [lochmueller/sourceopt#154]
you need to put $GLOBALS['TSFE']->config['config']['svgstore.']['fileSize'] ?? null into ( ) to work correctly

**Comment by xerc** [comment]
already @ https://github.com/lochmueller/sourceopt/commit/0a556f74ec49f5ed8930c7cab90b6088a2e9d8dd

**Comment by xerc** [comment]
@siwa-pparzer which version are you using ?

**Comment by xerc** [comment]
FIX @ https://github.com/lochmueller/sourceopt/pull/155/commits/ceec6fb8e87911cb2f95225c09cd3997bcef707a

**Comment by xerc** [comment]
this is a bit confusing cause it worked before ; https://github.com/lochmueller/sourceopt/commit/5cc52f34fda4bdb64d67d2cb30adbc707115fa26#diff-53672252530688feeb44861d96cf9081489a6b37247eb2730bc7f0cf6e0f936dL41

**Comment by lochmueller** [comment]
Fixed in current main branch.

**Comment by xerc** [comment]
btw/ did you include the TypoScript ?

**Comment by nebrot** [comment]
> did you include the TypoScript ? the array should be exist if TS is there ..

@xerc Thanks for this hint, this was probably the problem in my installation with TYPO3 13. We use a sitepackage with site sets and all other dependencies needed there like fluid-styled-content, redirects and seo-sitemap offer site sets which can be easily included. So the inclusion of sourceopt (setup.typoscript + constants.typoscript) was missing, i forgot it.
Would be cool if sourceopt also could offer a own site set. Because so i don't know how to include this external files in sitepackage, if it's not allowed/should be avoided (`@import statements are still fine to be used for local includes, but should be avoided for cross-set/extensions dependencies.` https://docs.typo3.org/m/typo3/reference-coreapi/13.4/en-us/ApiOverview/SiteHandling/SiteSets.html#loading-typoscript-via-the-site-package-s-set) or do you have an idea how to include configuration of "old" extensions without site sets in a sitepackage with site sets?

**Comment by xerc** [comment]
> `@import statements are still fine to be used for local includes, but should be avoided for cross-set/extensions dependencies`

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.1/Feature-103439-TypoScriptProviderForSitesAndSets.html
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.1/Feature-103437-IntroduceSiteSets.html#feature-103437-1712062105

**Comment by xerc** [comment]
@lochmueller do you have this integrated somewhere?

**Comment by lochmueller** [comment]
> @lochmueller do you have this integrated somewhere?

No. But I will check this in the near future for some extensions...
