### ISSUE TITLE
[Bug] PHP 7.4 & sourceopt 2.0.0 does have a bug

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/sourceopt#50]
I'm using:

TYPO3 v9.5.13
PHP v7.4.1
sourceopt v2.0.0

My typoscript contains this:

```
config {
  ##########################################
  ### Generator entfernen
  ########################################## 
  sourceopt{
    enabled = 1
    removeBlurScript = 1
    removeGenerator = 1
    removeComments = 1
    formatHtml = 1
    dropEmptySpaceChar = 1
  }
}
```

But when I render the frontend it just keeps the part `<meta name="generator" content="TYPO3 CMS" />`

**Comment by lochmueller** [comment]
I fixed the unit tests. The RemoveGenerator service seems to be right. The poblem is the calling prozess (perhaps)

**Comment by lochmueller** [comment]
Could you run some debugging in the middleware: CleanHtmlMiddleware

**Comment by MartinH0** [comment]
Will run it the next days on the newest dev version and report back.
How to run debugging in the middleware? Just turning on debug or anything special?

**Comment by lochmueller** [comment]
Check if the condition works:
https://github.com/lochmueller/sourceopt/blob/master/Classes/Middleware/CleanHtmlMiddleware.php#L35

if the right configuration is assigned (your TS):
https://github.com/lochmueller/sourceopt/blob/master/Classes/Middleware/CleanHtmlMiddleware.php#L43

and the return of the processed Output:
https://github.com/lochmueller/sourceopt/blob/master/Classes/Middleware/CleanHtmlMiddleware.php#L48

**Comment by lochmueller** [comment]
Hey Martin,
no feedback in the last days. I double checked this in my TYPO3 v 9 instance. First I missed to include the static TypoScript. After I include the Static TypoScript there are the right "$manipulations" objects in this place https://github.com/lochmueller/sourceopt/blob/master/Classes/Service/CleanHtmlService.php#L131 and the generator is also dropped.
Please test your env and create a new issue if you have some more details. I need ifnormation if this is a problem of the manipulation class or of the activation process, if the problem still exists. I close this issue, because I cannot rebuild this problem currently.
Regads,
Tim
