### ISSUE TITLE
include SVG parsing

### ISSUE THREAD

**Issue by xerc** [lochmueller/sourceopt#54]
there is a indentation issue with inline SVG
```
<path></path>
<path></path>
```
```
<path/>
  <path/>
```
---
```
<path></path>
<g>
  <path></path>
</g> </svg>
```
```
<path/><g>
    <path/></g> </svg>
```

> sourceopt.formatHtml = 4
> sourceopt.formatHtml.tabSize = 2

**Comment by lochmueller** [comment]
Hey @xerc 
I added a Unit test but cannot rebuild this problem: https://github.com/lochmueller/sourceopt/commit/ce223a8cf4c624f6420e60f413740defe0b3bdbc
Could you rebuild this problem with the UnitTest?
Regards,
Tim

**Comment by xerc** [comment]
this should illustrate the issue https://github.com/xerc/sourceopt/commit/4b18eb269f2d685d3d1980c3e0f3a5cfef3090bb
but there are many more; https://developer.mozilla.org/en-US/docs/Web/SVG/Element

**Comment by lochmueller** [comment]
Hey @xerc ,
thanks for the test. I merged it into my repo, but found no quick solution. Feel free to send a pull request. Currently I invest not much time into EXT:sourceopt because I do not use the extension by myself. Sorry... I have to prio other extensions (staticfilecache, calendarize etc.) befor sourceopt.
Regards,
Tim
