### ISSUE TITLE
Whitespaces

### ISSUE THREAD

**Issue by cepheiVV** [lochmueller/sourceopt#57]
When whitespaces get removed from a text, there's still one space before and one space after the text left:
```
<a> Label </a>
```

Expected behaviour: All whitespaces are removed around the text.

EXT:sourceopt v2.0.0
TYPO3 v10.4.4

**Comment by lochmueller** [comment]
Hey @cepheiVV ,

I think this is not possible. Or do you have a concept for clean up string like "Hello<a> World</a>" vs. "Hello <a>World</a>". Both are valid and if the whitespaces in a "a"-tag is removed, the first will result in "HelloWorld"... :-(

Best regards,
Tim

**Comment by cepheiVV** [comment]
@lochmueller 
I think GitHub escaped the HTML in your previous post. Or I can't follow what you mean...

**Comment by lochmueller** [comment]
Sorry... fixed :)

**Comment by cepheiVV** [comment]
Hm yes, both are valid. But one could argued that `Hello<a> World</a> ` is not optimised, which "sourceopt" implies to do. 
I'm not sure if anybody would even write such code intentionally. 
Also I never saw something alike in generated code. e.g. by the RTE.

**Comment by lochmueller** [comment]
Hmm... but where is the source off the `<a> Word </a>` problem in your case. It is useless/brocken in the template/RTE. I think SourceOpt is not the solution to build bad templates and the extension should not fix bugs. By design sourceopt could not delete single white spaces, because single whitespaces are used by the browser. Furthermore there is no parser that handle this and rewrite the HTML Output. So as result... it is very hard to handle and I don't know if sourceopt should handle such stuff.

**Comment by lochmueller** [comment]
Note: I also mentioned in other issues. I suggest NOT using sourceopt. There is no business value for the consumer of the website and a smart usage of `<f:spaceless>` is a mucch better approach :)

**Comment by cepheiVV** [comment]
The `<f:spaceless />` approach had no effect in my case.
That's why I gave  `EXT:sourceopt` a try.
My problem would be solved by changing https://github.com/lochmueller/sourceopt/blob/master/Classes/Service/CleanHtmlService.php#L351 to `$temp[$i] = preg_replace('/\s\s+/', '', $temp[$i]);`. (without the space in the replacement param)
I'll test if this has any negative effect in other areas of the website.
If not I'm just patching this line for my usecase.
